server.port=8081

spring.datasource.url=jdbc:h2:file:./data/paras_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jpa.show-sql=true
